# Generated by Django 3.1.2 on 2021-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('progress', models.PositiveIntegerField(verbose_name='Progress')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
